name: Build and Push 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Run ID
        id: get_id
        run: |
          response=$(curl https://api.github.com/repos/mzbgf/vscode-cpp/actions/runs)
          id=$(echo $response |  cut -d' ' -f8 | cut -d',' -f1)
          echo $id
          echo "::set-output name=id::$id"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip file
        run: zip -r release.zip ./.vscode 

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        id: upload_zip
        with:
          name: release
          path: release.zip

      - name: Get zip file link
        run: echo "https://github.com/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ steps.get_id.outputs.id }}"
        id: get_url  # 给步骤一个 ID
        
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          publish: true
          prerelease: false
          header: |
            Download the release [here](${{ steps.get_url.outputs.stdout }})!
            ${{ steps.get_url.outputs.stdout }}