name: Build and Push 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip file
        run: zip -r release.zip ./.vscode 

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip