name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Run ID
        id: get_id
        run: |
          response=$(curl https://api.github.com/repos/mzbgf/vscode-cpp/actions/runs)
          id=$(echo $response |  cut -d' ' -f8 | cut -d',' -f1)
          echo $id
          echo "::set-output name=id::$id"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip file
        run: zip -r release.zip ./.vscode 

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        id: upload_zip
        with:
          name: release
          path: release.zip

      - name: Get link
        run: echo "https://github.com/${{ github.repository }}/actions/runs/${{ steps.get_id.outputs.id }}"
        id: get_url  # 给步骤一个 ID
      
      - name: Create Release
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]'
